services:
  - type: web
    name: subtitle-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: ASSEMBLYAI_API_KEY
        sync: false
